### ISSUE TITLE
Obracanie zdjęć podczas scrollowania strony

### ISSUE THREAD

**Issue by martasiwinska** [martasiwinska/NeuroN-page#1]
Lewe zdjęcia w prawo
Prawie zdjęcia w lewo

**Comment by ProteanCode** [comment]
> > czy może ustawic to tak ze scoll uruchamia ten rotator dopiero na wysokości zdjęcia (tzn rotacja na jednym zdjeciu na jego wysokosci, rotacja drugiego na wyspokosci drugiego, rotacja 3 na wysokości 3

Zrobione
